### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#14]
The frontend sends too many and duplicate/unneeded requests on fast list scrolling, here a Pic:
<img width="1089" alt="Bildschirmfoto 2023-11-25 um 21 13 20" src="https://github.com/wrenger/schiller-lib/assets/77936078/b676c73b-3cd3-4427-85bc-86e932b1adbb">
(The rows with the same color are duplicate/unneeded requests)

Sadly, I cannot really recall in your code whats causing this but I think this should be fixed.

**Comment by wrenger** [comment]
This seems to happen with slower response times when requests overlap.
