### ISSUE TITLE
Rework

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#15]
I think we're pretty finished with the rework, only the README isn’t finished yet. We should be making the rework branch the default and the main the old/deprecated branch and shouldn't be merging rework into main. What do you think?

**Comment by wrenger** [comment]
Readme and branches have been updated. The only thing missing is the GitHub action for creating a release build.

**Comment by nwrenger** [comment]
GitHub action works now. I've also made a release build, please review that [here](https://github.com/wrenger/schiller-lib/releases/tag/0.9.0) and then this Issue can be closed.

**Comment by wrenger** [comment]
Looks good to me
