### ISSUE TITLE
Improve docs for gluer

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#20]
I think, we should add a note about `gluer` in the docs, for the building and dev process. The order of what you should build when needs to be addressed so that the building process won't fail, especially of the frontend.

**Comment by wrenger** [comment]
Good idea, do that :P

**Comment by nwrenger** [comment]
done in [this commit](https://github.com/wrenger/schiller-lib/commit/5dbac37ecf8cf0337434e15ec689b791a0e49c83)
