### ISSUE TITLE
Auto Convert umlauts

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#5]
A lot of younger students are using ä, ü and ö. We have to auto convert them when somebody creates a user because iServ uses ae, ue and oe for umlauts.

**Comment by wrenger** [comment]
Where in the program? When adding users?

**Comment by nwrenger** [comment]
exactly

**Comment by wrenger** [comment]
But using umlauts for the name is ok. Only the account usually has none (which is a convention for this specific school).
So you are proposing that in the account field, umlauts are replaced. Well, don't younger students know their accounts? They use them to log into iserv, or not?

Or do you mean the search for the user should also include the forename and surname, making it easier to find users.

**Comment by nwrenger** [comment]
They do use them, i think in both when creating accounts and when searching for them. We should disable making accounts that are not in iserv.

**Comment by wrenger** [comment]
Then what about guests or parents?

Maybe putting them in an extra Guest group might be a better Idea. This makes it easier to find and remove them later...

**Comment by wrenger** [comment]
In https://github.com/wrenger/schiller-lib/commit/57f3bd4b47aa9b2624863452892f752bac15ecc4 all manually entered users are now added to the '-' group. And there is a new advanced search to find users by group.

**Comment by nwrenger** [comment]
That makes it easier, I guess I have to explain the software to the schillerlib team again, so that wrong registrations are far less happening...
