### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#6]
When somebody is adding a user, automatically look if that user is a iServ account. When it is not, don't let to add the user (maybe give a list with similar iserv users). (Students are getting their iServ account directly when enrolling in school)

**Comment by wrenger** [comment]
Previously, this account export was not entirely complete. Thus, as a fallback, we had to allow manual entry.

**Comment by wrenger** [comment]
I've improved user management in general (#5, #7). Now manually added users (and old ones) are marked with the '-' role.

**Comment by nwrenger** [comment]
Sounds good, a list with similar looking iServ accounts would also be really helping.

**Comment by wrenger** [comment]
The search in the user file (when pressing the button next to the account input or pressing enter) now returns the user with the most similar account as in the input field. It is not perfect, but it might be enough; Especially combined with a better error message if an account already exists.
