### ISSUE TITLE
Delete Old Users

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#7]
Automatically delete Users that don't have iServ accounts.

**Comment by wrenger** [comment]
Some former students were still part of the school library. I didn't just want to remove them automatically.
I mean, they all have empty roles after synchronizing with the users.csv, so you can manually find and remove them.

But I suppose a new dialog for removing users, not in the users.csv, after synchronization might be helpful.

**Comment by wrenger** [comment]
They are now marked with the '-' role and can be searched for and deleted with the new advanced user search (https://github.com/wrenger/schiller-lib/commit/57f3bd4b47aa9b2624863452892f752bac15ecc4)

**Comment by nwrenger** [comment]
Looks good, that fixes this issue!
