### ISSUE TITLE
Fetching User Data v2

### ISSUE THREAD

**Issue by wrenger** [wrenger/schiller-lib#9]
The current way of fetching user data from a large CSV file (generated by ISERV) might not be sufficient for a web server anymore.

We could use the ISERV API directly to fetch usernames and emails. However, we then would specifically depend on ISERV, and schools without ISERV couldn't use this project.

The alternative would be to keep the CSV import and specify a path for this file when starting the webserver. In the UI, we only need a button to update all roles from the user file.

**Comment by nwrenger** [comment]
Also made a patch for the db for that: [commit](https://github.com/wrenger/schiller-lib/commit/6b35b699c7d348ee527328248f09e116584c933a)

**Comment by wrenger** [comment]
So we settled on the user CSV file then?

**Comment by nwrenger** [comment]
Yes, I guess so...as you always say: "Don't Change a Running System!". But we could update the export from iServ to be a CSV file and not a TXT file with a weird divider (→ "|")

**Comment by wrenger** [comment]
I don't say that _always_ ^^
Here it seems a lot of effort for a very small effect...
And does the divider really make a difference?

**Comment by nwrenger** [comment]
I mean it's quite an unusal character...
But if you mean we shouldn't, we can it leave it as is.
Shouldn't this be closed by now?
